### ISSUE TITLE
Tasks Priority 

### ISSUE THREAD

**Issue by timpur** [joysfera/arduino-tasker#3]
Wondering if its possible to add tasks with priority?

Example i add a timeout during running code and i want to make sure its at the top of priority?

I imagine this would work by each task has a priority number and tasker executes tasks in ascending order. Tasks with the same priority execute in order of added ?

This allows you to add tasks with different priority levels, if not stated priority default of 255 (0 is Highest) and since their all the same then they execute in order of added, thus this can work the same way currently.

Tell me your thoughts.
Tim.

**Comment by joysfera** [comment]
Priorities have just been implemented in https://github.com/joysfera/arduino-tasker/commit/ac03f7d68bb5003a56fcb5d73e567acb335b18d0

**Comment by timpur** [comment]
Awesome :)
