### ISSUE TITLE
Long intevals seems not work

### ISSUE THREAD

**Issue by ulrikkau** [joysfera/arduino-tasker#5]
I tried to make 3 minutes (3x60x1000) intervals, but it never triggered the task, while it worked for 30 second intervals. I assume it has  something to do with types. Maybe mention in instruction the longest interval. Otherwise nice and easy to use.

**Comment by joysfera** [comment]
The longest interval is 4294967 seconds. That's **71582 minutes** or 1193 hours or 49 days.

Try appending ``UL`` to the number passed in, like this: ``3*60*1000UL`` and let us know if it helps.

**Comment by joysfera** [comment]
I suppose the 1000**UL** helped.
